# Generated by Django 4.1.1 on 2022-09-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("order_number", models.PositiveIntegerField()),
                ("price_usd", models.PositiveIntegerField()),
                ("srok_postavki", models.DateField()),
                ("price_rub", models.FloatField()),
            ],
        ),
    ]
